services:
  headful-chrome-remote-puppeteer:
    image: ghcr.io/jutemp/headful-chrome-remote-puppeteer:latest
    ports:
      - 5900:5900
      - 9223:9223
      - 9229:9229
    restart: unless-stopped
